POST {{urlLocal}}/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "João da Silva",
  "telefone": "11989659321",
  "cpf": "79689054007",
  "email": "joas2@example.com",
  "dataNascimento": "1990-05-15",
  "genero": "MASCULINO",
  "endereco": {
    "logradouro": "Rua das Flores, 123",
    "bairro": "Centro",
    "cidade": {
      "id": "454"
    },
    "cep": "01234-567"
  },
  "situacao": true
}

###
GET {{urlLocal}}/cliente
Content-Type: application/json
Authorization: Bearer {{token}}


###
PUT {{urlLocal}}/cliente/8
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 8,
  "nome": "Douglas Eleutério",
  "cpf": "26421985025",
  "email": "joao-6@example.com",
  "telefone": "11867654321",
  "endereco": {
    "id": 8,
    "logradouro": "Rua das Flores, 123456",
    "numero": null,
    "complemento": null,
    "bairro": "Centro",
    "cidade": {
      "id": 454,
      "nome": "Alcântara",
      "estado": {
        "dataCriacao": "2024-06-12T23:18:15",
        "dataAtualizacao": "2024-06-12T23:18:15",
        "id": 10,
        "nome": "Maranhão",
        "codigoIBGE": "21",
        "uf": "MA"
      },
      "codigoIBGE": "2100204"
    },
    "cep": "01234-567"
  },
  "dataNascimento": "1990-05-15"
}

###
GET {{urlLocal}}/historico?search=idEntidadeGeradora==1

###
POST {{urlLocal}}/procedimento
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Teste",
  "valor": 800.00,
  "quantidadeSessoes": 3,
  "intervaloEntreSessoes": 15
}

###
POST {{urlLocal}}/aquisicao
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cliente": {
    "id": 1,
    "nome": "Douglas",
    "telefone": "62985606521",
    "cpf": "63135457028",
    "email": "dougl@mail.com",
    "dataNascimento": "1990-09-24",
    "genero": "MASCULINO",
    "endereco": {
      "logradouro": "Rua ABC",
      "bairro": "Centro",
      "cidade": {"id":  5545},
      "cep": "74919770"
    }
  },
  "procedimentos": [
    {
      "quantidadeSessoes": 5,
      "intervaloEntreSessoes": 45,
      "procedimentoOrigemId": 1
    },
    {
      "quantidadeSessoes": 5,
      "intervaloEntreSessoes": 45,
      "procedimentoOrigemId": 1
    }
  ],
  "dataAquisicao": "2024-06-13T21:05:41",
  "valorAquisicao": 1600,
  "valorDesconto": 0,
  "pagamentos": [
    {
     "dataPagamento":"2024-06-13T21:05:41",
     "valorPagamento": 1600.00,
     "formaPagamento":"CARTAO_CREDITO",
     "quantidadeParcelas": 1,
     "taxa": 0.00,
     "parcelas": [
       {
         "dataCredito": "2024-07-13",
         "valorCredito": 1600.00,
         "valorTaxa": 0.0,
         "isRecebido": false,
         "numeroParcela": 1
       }
     ]
    }
  ]
}

###
GET {{urlLocal}}/aquisicao/16
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{urlLocal}}/historico?search=idEntidadeGeradora==6&tipoEntidade==CLIENTE
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET {{urlLocal}}/historico/select?search=idEntidadeGeradora==6;tipoEntidade==CLIENTE&page=0&size=10&sort=id,desc&columns=id,tipoEvento,dataOcorrencia
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json, text/plain, */*


### Editando Aquisição, alterar intervalo entre sessões
PATCH {{urlLocal}}/aquisicao
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 4,
  "procedimentos": [
    {
      "id": 4,
      "quantidadeSessoes": 5
    }
  ]
}


### Lista Aquisições
GET {{urlLocal}}/aquisicao/select?search=situacao==true&page=0&size=10&sort=dataAquisicao,asc&columns=id,cliente.id,cliente.nome,dataAquisicao,valorAquisicao,procedimentos.id,procedimentos.nome
Content-Type: application/json
Authorization: Bearer {{token}}



### Criar Aquisicao
POST {{urlLocal}}/aquisicao
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "cliente": 1,
  "dataAquisicao": "2024-07-01",
  "valorAquisicao": 2000,
  "valorDesconto": 0,
  "pagamentos": [
    {
      "formaPagamento": "PIX",
      "valorPagamento": 2000,
      "taxa": 0,
      "dataPagamento": "2024-07-31T03:00:00.000Z"
    }
  ],
  "procedimentosDaAquisicao": [
    {
      "procedimentoOrigemId": 35,
      "nome": "Face",
      "intervaloEntreSessoes": 30,
      "valor": 2000,
      "quantidadeSessoes": 1,
      "procedimento": "Bioestimulador de colageno"
    }
  ]
}