<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
	<p>Prezado(a) <span id="usuario">${user}</span>,</p>
	<p>Informamos que esse e-mail é de teste.</p>
</body>
</html>


