package br.com.tresptecnologia.enumeration;

import lombok.Getter;

@Getter
public enum EProcedimento {

    BOTOX,
    BOTOX_NEFERTITI,
    LASER_LAVIEEN,
    PREENCHIMENTO,
    RINOMODELACAO,
    BIOESTIMULADOR_DE_COLAGENO,
    BOTOX_FULLFACE,
    BOTOX_SORRISO_GENGIVAL,
    DESING,
    DESING_COM_RENA,
    BUCO_NA_LINHA,
    DEPILACAO_A_LASER,
    LIMPEZA_DE_PELE_COMUM,
    LIMPEZA_DE_PELE_COM_DERMAPLANING,
    DERMAPLANING,
    DERMAPEN,
    MICROPIGMENTACAO,
    RETOQUE_MICROPIGMENTACAO,
    PELLING_QUIMICO,
    APLICACAO_VARIZES,
    APLICACAO_DE_ENZIMAS,
    LIPO_DE_PAPADA_ENZIMATICA,
    MASSAGEM_MODELADORA,
    MASSAGEM_RELAXANTE,
    MASSAGEM_DRENAGEM,
    MASSAGEM_PARA_FLACIDEZ,
    MASSAGEM_PARA_CELULITE,
    LIFT_FACIAL,
    RADIOFREQUENCIA,
    LIPOCAVITACAO,
    CONE_YNDU,
    SESSAO_DETOX,
    VENTOSATERAPIA,
    CONSULTA_NUTROLOGA,
    CONSULTA_DRA_RAFAELA,
    CONSULTA_DRA_LARA
}
