version: "3.7"

services:
  oracle-xe:
    container_name: oracle-xe
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle_data:/opt/oracle/oradata
    environment:
      - ORACLE_SID=XE
      - ORACLE_PWD=fox789789@!@!

volumes:
  oracle_data:
    external: true
    name: oracle_data