--liquibase formatted sql
--changeset douglas.ferreira:seed-procedimentos

INSERT INTO PROCEDIMENTO
VALUES (1, 1, sysdate, sysdate, 'Depilação a Lazer');
INSERT INTO PROCEDIMENTO
VALUES (2, 1, sysdate, sysdate, 'Botox');
INSERT INTO PROCEDIMENTO
VALUES (3, 1, sysdate, sysdate, 'Botox Nefertiti');
INSERT INTO PROCEDIMENTO
VALUES (4, 1, sysdate, sysdate, 'Laser Lavieen');
INSERT INTO PROCEDIMENTO
VALUES (5, 1, sysdate, sysdate, 'Preenchimento');
INSERT INTO PROCEDIMENTO
VALUES (6, 1, sysdate, sysdate, 'Rinomodelação');
INSERT INTO PROCEDIMENTO
VALUES (7, 1, sysdate, sysdate, 'Bioestimulador de colageno');
INSERT INTO PROCEDIMENTO
VALUES (8, 1, sysdate, sysdate, 'Botox Fullface');
INSERT INTO PROCEDIMENTO
VALUES (9, 1, sysdate, sysdate, 'Botox sorriso gengival');
INSERT INTO PROCEDIMENTO
VALUES (10, 1, sysdate, sysdate, 'Desing');
INSERT INTO PROCEDIMENTO
VALUES (11, 1, sysdate, sysdate, 'Desing com rena');
INSERT INTO PROCEDIMENTO
VALUES (12, 1, sysdate, sysdate, 'Buço na linha');
INSERT INTO PROCEDIMENTO
VALUES (13, 1, sysdate, sysdate, 'Limpeza de pele comum');
INSERT INTO PROCEDIMENTO
VALUES (14, 1, sysdate, sysdate, 'Limpeza de pele com dermaplaning');
INSERT INTO PROCEDIMENTO
VALUES (15, 1, sysdate, sysdate, 'Dermaplaning');
INSERT INTO PROCEDIMENTO
VALUES (16, 1, sysdate, sysdate, 'Dermapen');
INSERT INTO PROCEDIMENTO
VALUES (17, 1, sysdate, sysdate, 'Micropigmentação');
INSERT INTO PROCEDIMENTO
VALUES (18, 1, sysdate, sysdate, 'Retoque micropigmentação');
INSERT INTO PROCEDIMENTO
VALUES (19, 1, sysdate, sysdate, 'Pelling quimico');
INSERT INTO PROCEDIMENTO
VALUES (20, 1, sysdate, sysdate, 'Aplicação varizes');
INSERT INTO PROCEDIMENTO
VALUES (21, 1, sysdate, sysdate, 'Aplicação de enzimas');
INSERT INTO PROCEDIMENTO
VALUES (22, 1, sysdate, sysdate, 'Lipo de papada enzimatica');
INSERT INTO PROCEDIMENTO
VALUES (24, 1, sysdate, sysdate, 'Massagem modeladora');
INSERT INTO PROCEDIMENTO
VALUES (25, 1, sysdate, sysdate, 'Massagem relaxante');
INSERT INTO PROCEDIMENTO
VALUES (26, 1, sysdate, sysdate, 'Massagem drenagem');
INSERT INTO PROCEDIMENTO
VALUES (27, 1, sysdate, sysdate, 'Massagem para flacidez');
INSERT INTO PROCEDIMENTO
VALUES (28, 1, sysdate, sysdate, 'Massagem para celulite');
INSERT INTO PROCEDIMENTO
VALUES (29, 1, sysdate, sysdate, 'Lift facial');
INSERT INTO PROCEDIMENTO
VALUES (30, 1, sysdate, sysdate, 'Radiofrequencia');
INSERT INTO PROCEDIMENTO
VALUES (31, 1, sysdate, sysdate, 'Lipocavitação');
INSERT INTO PROCEDIMENTO
VALUES (32, 1, sysdate, sysdate, 'Cone yndu');
INSERT INTO PROCEDIMENTO
VALUES (33, 1, sysdate, sysdate, 'Sessão detox');

--changeset douglas.ferreira:seed-procedimentos_depilação_lazer
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (1, 1, 30, 1, 'Virilha Completa', 150);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (2, 1, 30, 1, 'Axilas', 70.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (3, 1, 30, 1, 'Virilha Completa', 150.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (4, 1, 30, 1, 'Virilha Simples', 100.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (5, 1, 30, 1, 'Buço', 40.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (6, 1, 30, 1, 'Rosto', 100.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (7, 1, 30, 1, 'Contorno DA Barba', 80.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (8, 1, 30, 1, 'Barba Completa', 150.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (9, 1, 30, 1, 'Meia Perna', 170.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (10, 1, 30, 1, 'Perna Completa', 300.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (11, 1, 30, 1, 'Costas', 200.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (12, 1, 30, 1, 'Abdomen', 150.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (13, 1, 30, 1, 'Toráx', 130.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (14, 1, 30, 1, 'Linha Alba', 40.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (15, 1, 30, 1, 'Nariz', 40.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (16, 1, 30, 1, 'Queixo', 40.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (17, 1, 30, 1, 'Costeletas', 40.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (18, 1, 30, 1, 'Testa', 40.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (19, 1, 30, 1, 'Nuca', 50.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (20, 1, 30, 1, 'Areola', 50.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (21, 1, 30, 1, 'Mãos,Pés e Dedos', 50.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (22, 1, 30, 1, 'Pescoço', 80.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (23, 1, 30, 1, 'Braço', 100.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (24, 1, 30, 1, 'Antebraço', 100.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (25, 1, 30, 1, 'Lombar', 100.00);
INSERT INTO REGIAO (ID, QUANTIDADE_SESSOES, INTERVALO_ENTRE_SESSOES, PROCEDIMENTO_ID, NOME, VALOR)
VALUES (26, 1, 30, 1, 'Gluteos', 100.00);

